### ISSUE TITLE
SSLErrors Connecting to VirusTotal API

### ISSUE THREAD

**Issue by ivanlei** [Yelp/threat_intel#35]
I've got python 2.7.10 and latest OpenSSL.
```shell
$ python --version
Python 2.7.10
$ python -c 'import ssl; print ssl._OPENSSL_API_VERSION'
(1, 0, 2, 3, 15)
```
But still I get this.
```
Traceback (most recent call last):
  File "/Users/ivanlei/virtual_envs/osxcollector/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/ivanlei/virtual_envs/osxcollector/lib/python2.7/site-packages/grequests.py", line 71, in send
    self.url, **merged_kwargs)
  File "/Users/ivanlei/virtual_envs/osxcollector/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/ivanlei/virtual_envs/osxcollector/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/ivanlei/virtual_envs/osxcollector/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
<Greenlet at 0x12ac6b050: <bound method AsyncRequest.send of <grequests.AsyncRequest object at 0x12b947790>>(stream=False)> failed with SSLError
```

I've got a branch where I've explored things a bit and I think I have a fix.

**Comment by krmaxwell** [comment]
This should've been closed when #36 was merged, right?

**Comment by kurtcoke** [comment]
I still get this error. Using the latest version.
